# -*- coding: utf-8 -*-
"""17_June_TF_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rQmmpCXZjkB1kKgPycfEiRgvyN7vQLW0
"""

import tensorflow as tf

x=10
type(x)

t1=tf.constant(10)
t2=tf.Variable(10)
print(type(t1),t1,t1.numpy())
print(type(t2),t2,t2.numpy())

t2.assign(20).numpy()

t1.assign(20)

t2.assign_add(5).numpy()

t2=t2+5

t2.numpy()

t2=t2*2
t2.numpy()

t1*5

t=tf.constant(5)

t=t+5

t.numpy()

t.assign_add(5)

