# -*- coding: utf-8 -*-
"""18_June_tf2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jVqrG1i_IEz7c4uloW3eBFbeDjjlOlu_
"""

import tensorflow as tf
import numpy as np

t1=tf.constant([10,20,30])
t1=tf.constant(range(10))
t1=tf.constant(np.arange(5))

t2=tf.Variable([10,20,30])
t2=tf.Variable(range(10))
t2=tf.Variable(np.arange(5))

t3=tf.constant([[10,20,30],[20,30,40]])
t3=tf.constant([10,20,30,40,50,60],shape=(2,3))
t3.numpy()

t3=tf.constant([10,20,30,40,50,60],shape=(2,3),dtype='float32')
t3.numpy()

t3=tf.constant([10,20,30,40,50,60],shape=(2,3),dtype='float32',name='age_const_tensor')
t3.numpy()

t3=tf.Variable([[10,20,30],[40,50,60]],dtype='float32',name='age_const_tensor')
t3.numpy()

t1=tf.constant([10,20,-5,50,40,30,20])
t2=tf.constant([40,20,-2,10,40,30,20])
print(tf.math.minimum(t1,t2))
print(tf.math.reduce_min(t1))
print(tf.math.maximum(t1,t2))
print(tf.math.reduce_max(t1))

tf.math.reduce_sum(t1)

tf.math.reduce_mean(t1)

tf.math.argmax(t1)

tf.math.argmin(t1)

m1=tf.constant([[1,2],[3,4]])
m2=tf.constant([[10,20],[30,40]])
print(tf.math.multiply(m1,m2))
print(tf.matmul(m1,m2))
print(m1*m2)
print(m1@m2)

tf.reduce_min(t1)

m1=np.random.randint(1,100,(1000,1000))
m2=np.random.randint(1,100,(1000,1000))
t1=tf.constant(m1)
t2=tf.constant(m2)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# m1@m2

# Commented out IPython magic to ensure Python compatibility.
# %%time
# t1@t2

tf.random.normal(shape=(30,))

tf.random.truncated_normal(shape=(30,))

tf.random.uniform(shape=(30,))



