# -*- coding: utf-8 -*-
"""28_June_Multi_Classification_HiddenLayers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v9nW-yZmMg45ZoeHKw3EVDJQb-keNDJd
"""

import pandas as pd
import tensorflow as tf
from sklearn.metrics import accuracy_score

df=pd.read_csv('sample_data/mnist_train_small.csv',header=None)
X=df.iloc[:,1:].values
y=df.iloc[:,0].values

def output_neuron(X,w,b):
  return tf.matmul(X,w)+b

def loss(y_true,logits):
  return tf.reduce_mean(tf.losses.sparse_categorical_crossentropy(y_true,logits))

def activation_hidden(ynet):
  return tf.nn.tanh(ynet)

def activation_output(ynet):
  return tf.nn.softmax(ynet)

tf.random.set_seed(10)

wh1=tf.Variable(tf.random.truncated_normal(shape=[784,300],dtype=tf.double))
bh1=tf.Variable(tf.random.truncated_normal(shape=[300],dtype=tf.double))

wh2=tf.Variable(tf.random.truncated_normal(shape=[300,150],dtype=tf.double))
bh2=tf.Variable(tf.random.truncated_normal(shape=[150],dtype=tf.double))

wo=tf.Variable(tf.random.truncated_normal(shape=[150,10],dtype=tf.double))
bo=tf.Variable(tf.random.truncated_normal(shape=[10],dtype=tf.double))

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=df.iloc[:,1:].values
y=df.iloc[:,0].values
X_new=sc.fit_transform(X)
optimizer=tf.optimizers.SGD(learning_rate=.1)
for epoch in range(2000):
  with tf.GradientTape() as tape:
    ynet=output_neuron(X_new,wh1,bh1)
    logits=activation_hidden(ynet)

    ynet=output_neuron(logits,wh2,bh2)
    logits=activation_hidden(ynet)

    ynet=output_neuron(logits,wo,bo)
    logits=activation_output(ynet)

    ls=loss(y,logits)
    yhat=tf.argmax(logits,1)
    if(epoch%100==0):
      print(ls,accuracy_score(y,yhat))
    gradients=tape.gradient(ls,[wo,bo,wh2,bh2,wh1,bh1])
    optimizer.apply_gradients(zip(gradients,[wo,bo,wh2,bh2,wh1,bh1]))

df_test=pd.read_csv('sample_data/mnist_test.csv',header=None)
df_test.shape

import cv2
gray=cv2.imread('7.png',0)
gray=gray.reshape(1,-1)
gray=sc.transform(gray)

ynet=output_neuron(gray,wh1,bh1)
logits=activation_hidden(ynet)

ynet=output_neuron(logits,wh2,bh2)
logits=activation_hidden(ynet)

ynet=output_neuron(logits,wo,bo)
logits=activation_output(ynet)

pred=tf.argmax(logits,1)
print(pred)

